[package]
name = "common_structs"
version = "0.1.0"
edition = "2021"

[dependencies]
leaf = { path = "src/leaf" }
message = { path = "src/message" }
types = { path = "src/types" }

[features]
debug = ["leaf/debug"]