[package]
name = "common_structs"
version = "0.1.0"
edition = "2021"

[dependencies]
leaf = { path = "leaf" }
message = { path = "message" }
types = { path = "alias_types" }

[features]
debug = ["leaf/debug"]