[package]
name = "leaf"
version = "0.1.0"
edition = "2021"

[dependencies]
wg_2024 = { git = "https://github.com/WGL-2024/WGL_repo_2024.git"}
crossbeam-channel = ">=0.5.13"
message = { path = "../message" }
types = { path = "../alias_types" }

[features]
debug = ["wg_2024/debug"]